name: "Sync `config.js` to Template Repository"

on:
  workflow_dispatch: { }
  push:
    paths:
      - docs/config.js
      - docs/sync.yaml
      - .github/workflows/sync-docs-changes.yaml

jobs:
  sync-to-template-repo:
    name: "Sync `config.js` to Template Repository"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Source Repository"
        uses: "actions/checkout@v3"
        with:
          repository: "jmuchovej/paperpile-notion"
          path: "pn"
          token: ${{ secrets.PAPERPILE_REPO_PAT }}

      - name: "Checkout Template Repository"
        uses: "actions/checkout@v3"
        with:
          repository: "jmuchovej/sync-paperpile-to-notion"
          path: "st"
          token: ${{ secrets.PAPERPILE_REPO_PAT }}

      - name: "Sync `config.js` changes"
        shell: "bash"
        run: |
          rsync -av --progress ./pn/docs/config.js ./st/.config/paperpile-notion/config.js
          rsync -av --progress ./pn/docs/sync.yaml ./st/.github/workflows/sync.yaml

      - name: "Commit `config.js` Changes to Template Repository"
        uses: "endbug/add-and-commit@v9"
        with:
          message: "✨ Sync `config.js` and `sync.yaml` changes with upstream"
          committer_name: "GitHub Actions"
          committer_email: "actions@github.com"
          cwd: "./st/"
          add: >-
            .config/paperpile-notion/config.js
            .github/workflows/sync.yaml
