name: "Sync `config.js` to Template Repository"

on:
  workflow_dispatch: { }
  push:
    paths:
      - docs/config.js
      - .github/workflows/sync-config.js.yaml

jobs:
  sync-to-template-repo:
    name: "Sync `config.js` to Template Repository"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Source Repository"
        uses: "actions/checkout@v3"
        with:
          repository: "${{ github.repository }}"
          path: "pn"

      - name: "Checkout Template Repository"
        uses: "actions/checkout@v3"
        with:
          repository: "jmuchovej/sync-paperpile-to-notion"
          path: "st"

      - name: "Sync `config.js` changes"
        shell: "bash"
        run: |
          cp ./pn/docs/config.js ./st/.config/paperpile-notion/config.js

      - name: "Commit Changes to Template Repository"
        shell: "bash"
        run: |
          cd ./st

          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh auth setup-git

          git config user.name "John Muchovej"
          git checkout -b jmuchovej/update-config.js

          git add .config/paperpile-notion/config.js
          git commit -m "🔧 Update \`config.js\` to reflect latest release configuration"

          git push origin jmuchovej/update-config.js
          gh pr --fill
